name: Unit tests

on:
  push:
  workflow_dispatch: # Run this workflow manually from the Actions tab

# On new push, cancel any in-progress runs of this workflow on the same branch.
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Shared Python/UV setup
        uses: ./.github/actions/setup-environment
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run ruff check
        if: success() || failure()
        run: uv run ruff check

      - name: Run mypy check
        if: success() || failure()
        run: uv run mypy --strict src

      - name: Run pylint test
        if: success() || failure()
        run: uv run pylint src

      - name: Run unit tests
        if: success() || failure()
        run: uv run pytest
